network:
  interfaces:
    # Транзит в сторону InetRouter
    ens19:
      addresses: ["192.168.255.2/30"]

    # uplink в сторону R1 (VLAN100)
    vlan100:
      id: 100
      link: "ens19"
      addresses: ["192.168.255.9/30"]

    # сеть office1
    ens18:
      addresses: ["192.168.2.1/24"]

  static_routes:
    - to: "0.0.0.0/0"
      via: "192.168.255.1"    # default → InetRouter

forwarding: true
nat:
  enabled: false
