network:
  interfaces:
    ens18:
      addresses: ["192.168.250.101/24"]
      gateway: "192.168.250.1"
      nameservers:
        - 8.8.8.8
        - 1.1.1.1
    ens19:
      addresses: ["192.168.255.1/30"]   # link to CentralRouter
  static_routes:
    - to: "192.168.0.0/16"
      via: "192.168.255.2"              # CentralRouter

nat:
  enabled: true
  external_interface: "ens18"

forwarding: true
