network:
  interfaces:
    # uplink VLAN100
    vlan100:
      id: 100
      link: "ens19"
      addresses: ["192.168.255.10/30"]
      gateway: "192.168.255.9"
      nameservers:
        - 8.8.8.8
        - 1.1.1.1

    # сеть Office1
    eth1:
      addresses: ["192.168.2.129/24"]

forwarding: true
nat:
  enabled: false
