network:
  version: 2
  renderer: networkd
  ethernets:
    ens18:
      dhcp4: false
      addresses: [192.168.250.123/24] # mgmt

    ens19:
      dhcp4: false

    ens20:
      dhcp4: false
      mtu: 1500

  vlans:


    vlan100:
      id: 100
      link: ens19
      addresses: [192.168.255.10/30]
      routes:
        - to: default
          via: 192.168.255.9          # Uplink to CentralRouter
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1

    vlan2210:
      id: 2210
      link: ens20
      addresses: [192.168.2.129/26]     # Office1Server Managers network

    vlan2220:
      id: 2220
      link: ens20
      addresses: [192.168.2.192/26]     # Office1Hardware network

    vlan2230:
      id: 2230
      link: ens20
      addresses: [192.168.2.65/26]      # Office1 test servers network

    vlan2240:
      id: 2240
      link: ens20
      addresses: [192.168.2.1/26]     # Office1 dev network
