network:
  interfaces:
    # uplink VLAN2200 192.168.255.6/30
    vlan200:
      id: 200
      link: "ens19"
      addresses: ["192.168.255.6/30"]
      gateway: "192.168.255.5"
      nameservers:
        - 8.8.8.8
        - 1.1.1.1

    # офисная сеть Office2 
    eth1:
      addresses: ["192.168.2.193/26"]

forwarding: true
nat:
  enabled: false
