network:
  version: 2
  renderer: networkd
  ethernets:
    ens18:
      dhcp4: false
      addresses: [192.168.240.224/24] # mgmt

    ens19:
      dhcp4: false

    ens20:                            # trunk port
      dhcp4: false
      mtu: 1500

  vlans:
    vlan2200:
      id: 2200
      link: ens19
      addresses: [192.168.255.6/30]
      routes:
        - to: default
          via: 192.168.255.5          # Uplink to CentralRouter
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1

    vlan310:
      id: 310
      link: ens20
      addresses: [192.168.1.1/25]     # Office2Server Managers network

    vlan320:
      id: 320
      link: ens20
      addresses: [192.168.1.193/26]   # Office2 Hardware network

    vlan330:
      id: 330
      link: ens20
      addresses: [192.168.1.129/26]   # Office2 test servers network
